Update halo.txt
sagut-obda/latihan-git pull request #2
Opened 2017-10-30 12:30 UTC by IrvanHardyanto98

menambahkan satu baris berisi nama anggota kelompok

2017-10-30 13:41 UTC, chez14 commented
Nice one, Hardyanto!

Setiap review dan issue bakal muncul di email lu, *just in case* kalo lu jarang buka Githubnya.

2017-10-30 13:42 UTC, chez14 commented on halo.txt
> +1. Irvan H
Coba taro ke paling bawah, tanpa nomor, cukup nama aja...

Ini contoh gw ngereview kodingan temen-temen lain, lain kesempatan, gw coba biarin lu ngerasain buat ngereview kodingan yang lain :)

2017-10-30 13:42 UTC, chez14 requested changes
Memperbaiki konsistensi kode dan format

2017-10-31 07:03 UTC, IrvanHardyanto98 commented
hmm begitu bukan maksudnya?

2017-10-31 07:49 UTC, chez14 commented
Bukan van, dia taro di bawah
```
 Eh tapi jangan lupa bikin branch baru dulu, baru dicommit, trus baru dipush.
```
tapi yang nomornya itu udah bener... 😁

2017-10-31 13:04 UTC, chez14 approved these changes

2017-10-31 13:04 UTC, chez14 commented
Yay, thanks Van, sudah oke, gw merge sekarang.

2017-10-31 13:05 UTC, merged